version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "3000:3000"
      - "27017:27017"
      - "8081:8081"
